version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - JWT_SECRET=superSecretFarah
      - DB_NAME=support
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=support
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
