pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "devops-ticket-backend"
        REGISTRY = "localhost:5050"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'docker run ${DOCKER_IMAGE} npm test'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker-compose up -d'
                }
            }
        }
    }
}
