pipeline {
    agent any

    tools {
        nodejs 'NodeJS 18'
    }

    environment {
        PORT = '5050'
        JWT_SECRET = 'superSecretFarah'
        DB_NAME = 'support'
        DB_USER = 'postgres'
        DB_PASSWORD = 'pass'
        DB_HOST = 'localhost'
        DB_PORT = '5432'
    }

    stages {
        stage('Cloner le repo') {
            steps {
                git branch: 'seb-docker', credentialsId: 'github-token', url: 'https://github.com/farahyasmine/PROJET-DEVOPS.git'
            }
        }

        stage('Installer les dépendances') {
            steps {
                dir('backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Vérifier le code') {
            steps {
                dir('backend') {
                    bat '''
                    powershell -Command "Start-Process node index.js -WindowStyle Hidden"
                    timeout /t 5
                    curl -f http://localhost:5050/ping
                    powershell -Command "Get-Process node | Stop-Process -Force"
                    '''
                }
            }
        }
    }
}